---
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
fontsize: 12pt 
editor_options: 
  chunk_output_type: console
---

<font size="4">

---

<div class="alert alert-success">

### Before the course starts

- Make sure you install all the software we will be using [as detailed in here](https://marce10.github.io/OTS_BIR_2023/course_prep.html)

&nbsp; 

**Refresh basic R concepts**
<a href="https://marce10.github.io/OTS_BIR_2023/r_basics.html" class="btn btn-warning btn-xs" role="button">R basics</a>

-   Object types in R
-   Subsetting
-   Style matters
-   R documentation

&nbsp; 

</div>

&nbsp;

## Day 1 [(video)](https://www.youtube.com/watch?v=tHEKaQr95jk)

--- 

<div class="alert alert-warning">

### Readings 

#### Intro to basic bioacoustics concepts

- Köhler, J., Jansen, M., Rodríguez, A., Kok, P. J. R., Toledo, L. F., Emmrich, M., ... & Vences, M. (2017). [The use of bioacoustics in anuran taxonomy: theory, terminology, methods and recommendations for best practice](http://www.mvences.de/p/p1/Vences_A354.pdf). Zootaxa, 4251(1), 1-124. (*at least the first 28 pages*)


### Videos

- [Introduction to digital audio](https://www.youtube.com/watch?v=24BnHsY6rQs)

- Digital audio artifacts: ([Video 1](https://www.youtube.com/watch?v=GwYTtSd8bTU), [Video 2](https://www.youtube.com/watch?v=thw32YvLrYo))

&nbsp; 

### Optional readings

#### Reproducibility

- Alston, J. M., & Rick, J. A. (2021). [A beginner’s guide to conducting reproducible research](http://jessicarick.com/s/Alston_ReproducibleResearch_BulletinESA_Rev1.pdf). Bulletin of the Ecological Society of America, 102(2), 1-14.
- Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). [Low availability of code in ecology: A call for urgent action](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000763). PLoS Biology, 18(7), e3000763.

</div>

&nbsp; 


**Introduction**
<a href="https://marce10.github.io/OTS_BIR_2023/introduction.html" class="btn btn-warning btn-xs" role="button">Introduction</a>

-   How animal acoustic signals look like?
-   Analytical workflow in bioacoustics research
-   Advantages of programming
-   Course outline

&nbsp; 

**What is sound?**
<a href="https://marce10.github.io/OTS_BIR_2023/sound.html" class="btn btn-warning btn-xs" role="button">Sound</a>

<div class="alert alert-warning">

- Create a Rstudio project for the course 

- Download [this folder](https://www.dropbox.com/sh/87qx2ckr047dcru/AAAIIJZdoca3T4-3sUYmrB4xa?dl=0) into the course project directory

</div>

-   Sound as a time series
-   Sound as a digital object
-   Acoustic data in R
-   ‘wave’ object structure
-   ‘wave’ object manipulations
-   additional formats

&nbsp; 

<div class="alert alert-info">

### Homework

1. Use the function `query_xc()` to check the availability of recordings for any bird species (do not download at this step) ([*check this brief tutorial on how to do that*](https://marce10.github.io/OTS_BIR_2023/get_xc_recordings.html))

1. Subset the data frame returned by the function to get a subset of subspecies/populations or recordings from a specific country and for certain vocalization type (using base R subsetting tools)

1. Download the associated recordings using `query_xc()` again

1. Explore the recordings with any spectrogram creating GUI program

</div>

---

&nbsp; 

## Day 2 [(video)](https://youtu.be/_IR0-oJEm_E)

---

<div class="alert alert-warning">

### Videos 

#### Raven tutorials

- [Introduction to the Raven Pro Interface](https://ravensoundsoftware.com/video-tutorials/english/01-introduction-to-the-raven-pro-interface/)
- [Introduction to selections and measurements](https://ravensoundsoftware.com/video-tutorials/english/02-selections-and-measurements/)
- [Saving, retrieving, and exporting selection tables](https://ravensoundsoftware.com/video-tutorials/english/03-saving-selection-tables/)
- [Using annotations](https://ravensoundsoftware.com/video-tutorials/english/05-using-annotations/)

</div>

**Building spectrograms**
<a href="https://marce10.github.io/OTS_BIR_2023/spectrograms.html" class="btn btn-warning btn-xs" role="button">Building
spectrograms</a>

-   Fourier transform
-   Building a spectrogram
-   Characteristics and limitations
-   Spectrograms in R

**Package seewave**
<a href="https://marce10.github.io/OTS_BIR_2023/seewave.html" class="btn btn-warning btn-xs" role="button">seewave</a>

-   Explore, modify and measure ‘wave’ objects
-   Spectrograms and oscillograms
-   Filtering and re-sampling
-   Acoustic measurements

&nbsp; 

<div class="alert alert-info">

### Homework

1. Use Raven Pro to annotate some of the signals found in the xeno-canto recordings you downloaded previously

</div>

---

&nbsp;

## Day 3 [(video)](https://youtu.be/DNhUINQrcWI)

---

<div class="alert alert-warning">

### Readings 

- Arasco, A. G., Manser, M., Watson, S. K., Kyabulima, S., Radford, A. N., Cant, M. A., & Garcia, M. (2023). [Testing the acoustic adaptation hypothesis with vocalizations from three mongoose species](https://www.sciencedirect.com/science/article/pii/S0003347222000574). Animal Behaviour, 187, 71-95.

</div>

&nbsp; 

**Annotation software**
<a href="https://marce10.github.io/OTS_BIR_2023/annotations.html" class="btn btn-warning btn-xs" role="button">annotations</a>

-   Raven / audacity
-   Open and explore recordings
-   Modify-optimize visualization parameters
-   Annotate signals

**Quantifying acoustic signal structure**
<a href="https://marce10.github.io/OTS_BIR_2023/measure_acoustic_structure.html" class="btn btn-warning btn-xs" role="button">Quantify structure</a>

-   Spectro-temporal measurements (`spectro_analysis()`)
-   Parameter description
-   Harmonic content
-   Cepstral coefficients (`mfcc_stats()`)
-   Cross-correlation (`cross_correlation()`)
-   Dynamic time warping (`freq_DTW()`)
-   Signal-to-noise ratio (`sig2noise()`)
-   Inflections (`inflections()`)
-   Parameters at other levels (`song_analysis()`)

&nbsp; 

<div class="alert alert-info">

### Homework

1. Double-check annotations using warbleR's dedicated functions
  - Create single spectrograms of each annotation
  - Create full spectrograms of all sound files along with annotations
  - Create catalogs

&nbsp; 

2. Double-check annotations using Raven (export data from R to Raven)

</div>


---

&nbsp; 

## Day 4 [(video)](https://youtu.be/Ua9xHNuhkN0)

---

<div class="alert alert-warning">

### Readings 

#### 

- Odom, K. J., Cain, K. E., Hall, M. L., Langmore, N. E., Mulder, R. A., Kleindorfer, S., ... & Webster, M. S. (2021). [Sex role similarity and sexual selection predict male and female song elaboration and dimorphism in fairy‐wrens](https://onlinelibrary.wiley.com/doi/pdf/10.1002/ece3.8378). Ecology and evolution, 11(24), 17901-17919.


</div>

&nbsp; 

**Quality control in recordings and annotation**
<a href="https://marce10.github.io/OTS_BIR_2023/quality_checks.html" class="btn btn-warning btn-xs" role="button">Quality checks</a>

-   Check and modify sound file format (`check_wavs()`, `info_wavs()`,
    `duration_wavs()`, `mp32wav()` y `fix_wavs()`)
-   Tuning spectrogram parameters (`tweak_spectro()`)
-   Double-checking selection tables (`check_sels()`, `spectrograms()`,
    `full_spectrograms()` & `catalog()`)
-   Re-adjusting selections (`tailor_sels()`)


**Characterizing hierarchical levels in acoustic signals**

-   Creating ‘song’ spectrograms (`full_spectrograms()`,
    `spectrograms()`)
-   ‘Song’ parameters (`song_analysis()`)

&nbsp; 

<div class="alert alert-info">

### Homework

1. Select best quality signals for analysis
1. Measure acoustic parameters
1. Summarize variation at higher hierachical levels (if necessary)

</div>

---

&nbsp; 

## Day 5 [(video)](https://youtu.be/eABOp_TF_A8)

---

<div class="alert alert-warning">

### Readings 

- Blog post: [Potential issues of the 'spectral parameters/PCA' approach](https://marce10.github.io/2018/07/04/Issues_spectral_parameters-PCA.html)

- Blog post: [Choosing the right method for measuring acoustic signal structure](https://marce10.github.io/2017/02/17/Choosing_the_right_method_for_measuring_acoustic_signal_structure.html)

</div>

&nbsp; 


**Choosing the right method for quantifying structure**
<a href="https://marce10.github.io/OTS_BIR_2023/comparing_methods.html" class="btn btn-warning btn-xs" role="button">Comparing methods</a>

-   Compare different methods for quantifying structure
    (`compare_methods()`)

**Quantifying acoustic spaces**
<a href="https://marce10.github.io/OTS_BIR_2023/acoustic_space.html" class="btn btn-warning btn-xs" role="button">Acoustic space</a>

- Intro to PhenotypeSpace 
- Quanitfying space size
- Comparing sub-spaces

&nbsp; 


```{r, eval = FALSE, echo = FALSE}

**Automatic detection**
<a href="https://marce10.github.io/OTS_BIR_2023/ohun.html" class="btn btn-warning btn-xs" role="button">Automatic detection</a>

-   ohun package for optimize acoustic signal detection
-   Detection using amplitude, frequency, and time filters
    (`ohun::energy_detector()`)
-   Detection using cross-correlation (`ohun::template_detector()`)
-   Frequency range detection (`warbleR::freq_range()` and `warbleR::freq_range_detec()`)

**Package warbleR**
<a href="https://marce10.github.io/OTS_BIR_2023/intro_to_warbler.html" class="btn btn-warning btn-xs" role="button">Intro
to warbleR</a>

-   Intro to warbleR
-   Selection tables
-   Extended selection tables
-   Selection table manipulation
-   warbleR functions and the bioacoustics analysis workflow

- Gibb, R., Browning, E., Glover‐Kapfer, P., & Jones, K. E. (2019). [Emerging opportunities and challenges for passive acoustics in ecological assessment and monitoring](https://besjournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/2041-210X.13101). Methods in Ecology and Evolution, 10(2), 169-185.´

#### Signal transmission

- Graham, B. A., Sandoval, L., Dabelsteen, T., & Mennill, D. J. (2017). [A test of the Acoustic Adaptation Hypothesis in three types of tropical forest: degradation of male and female Rufous-and-white Wren songs](https://www.tandfonline.com/doi/pdf/10.1080/09524622.2016.1181574?casa_token=AzHx1ABmGXUAAAAA:f33oQnqbUrBR2q6om8FmkKjRNOxN_WDQqIa1Szly_rdUlvV4pLffuFXZtWyj6T6FQyV5NhVqIdwOITZqKw). Bioacoustics, 26(1), 37-61.

- Dabelsteen, T., Larsen, O. N., & Pedersen, S. B. (1993). [Habitat‐induced degradation of sound signals: Quantifying the effects of communication sounds and bird location on blur ratio, excess attenuation, and signal‐to‐noise ratio in blackbird song](https://www.academia.edu/download/72224403/eed203af725673bae94999ae0258049db24c.pdf). The Journal of the Acoustical Society of America, 93(4), 2206-2220. (*Mostly to get the definitions of the degradation metrics used in Graham et al. 2017*)
```

