---
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
fontsize: 12pt 
editor_options: 
  chunk_output_type: console
---


<font size="4">

## Day 1

--- 

<div class="alert alert-warning">

### Readings 

#### Reproducibility

- Alston, J. M., & Rick, J. A. (2021). [A beginner’s guide to conducting reproducible research](http://jessicarick.com/s/Alston_ReproducibleResearch_BulletinESA_Rev1.pdf). Bulletin of the Ecological Society of America, 102(2), 1-14.
- Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). [Low availability of code in ecology: A call for urgent action](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000763). PLoS Biology, 18(7), e3000763.

#### Intro to basic bioacoustics concepts

- Köhler, J., Jansen, M., Rodríguez, A., Kok, P. J. R., Toledo, L. F., Emmrich, M., ... & Vences, M. (2017). [The use of bioacoustics in anuran taxonomy: theory, terminology, methods and recommendations for best practice](http://www.mvences.de/p/p1/Vences_A354.pdf). Zootaxa, 4251(1), 1-124. (*at least the first 28 pages*)


### Videos

- [Introduction to digital audio](https://www.youtube.com/watch?v=24BnHsY6rQs)

- Digital audio artifacts: ([Video 1](https://www.youtube.com/watch?v=GwYTtSd8bTU), [Video 2](https://www.youtube.com/watch?v=thw32YvLrYo))

</div>

&nbsp; 


**Introduction**
<a href="https://marce10.github.io/OTS_BIR_2023/introduction.html" class="btn btn-warning btn-xs" role="button">Introduction</a>

-   How animal acoustic signals look like?
-   Analytical workflow in bioacoustics research
-   Advantages of programming
-   Course outline

**Basic R concepts**
<a href="https://marce10.github.io/OTS_BIR_2023/r_basics.html" class="btn btn-warning btn-xs" role="button">R basics</a>

-   Object types in R
-   Subsetting
-   Style matters
-   R documentation

&nbsp; 

<div class="alert alert-info">

### Project assignment

1. Use the function `query_xc()` to check the availability of recordings for some bird species you have in mind for your project (do not download at this step) ([*check this brief tutorial on how to do that*](https://marce10.github.io/OTS_BIR_2023/get_xc_recordings.html))

1. Subset the data frame returned by the function to get the subspecies/populations and vocalization type you are interested in (using base R subsetting tools)

1. Download the associated recordings using `query_xc()` again

</div>

---

&nbsp; 

## Day 2

---

<div class="alert alert-warning">

### Videos 

#### Raven tutorials

- [Introduction to the Raven Pro Interface](https://ravensoundsoftware.com/video-tutorials/english/01-introduction-to-the-raven-pro-interface/)
- [Introduction to selections and measurements](https://ravensoundsoftware.com/video-tutorials/english/02-selections-and-measurements/)
- [Saving, retrieving, and exporting selection tables](https://ravensoundsoftware.com/video-tutorials/english/03-saving-selection-tables/)
- [Using annotations](https://ravensoundsoftware.com/video-tutorials/english/05-using-annotations/)

</div>

&nbsp; 

**What is sound?**
<a href="https://marce10.github.io/OTS_BIR_2023/sound.html" class="btn btn-warning btn-xs" role="button">Sound</a>

<div class="alert alert-warning">

- Create a Rstudio project for the course 

- Download [this folder](https://www.dropbox.com/sh/447h1afgdcldai6/AACqP5hCv-FfDEk9C1bWRNMva?dl=0) into the course project directory

</div>

-   Sound as a time series
-   Sound as a digital object
-   Acoustic data in R
-   ‘wave’ object structure
-   ‘wave’ object manipulations
-   additional formats

&nbsp; 

<div class="alert alert-info">

### Project assignment

1. Annotate target signals using Raven Pro (a subset of the recordings if working on automatic detection)

</div>

---

&nbsp;

## Day 3

---

<div class="alert alert-warning">

### Readings 

- Gibb, R., Browning, E., Glover‐Kapfer, P., & Jones, K. E. (2019). [Emerging opportunities and challenges for passive acoustics in ecological assessment and monitoring](https://besjournals.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/2041-210X.13101). Methods in Ecology and Evolution, 10(2), 169-185.


</div>

&nbsp; 

**Building spectrograms**
<a href="https://marce10.github.io/OTS_BIR_2023/spectrograms.html" class="btn btn-warning btn-xs" role="button">Building
spectrograms</a>

-   Fourier transform
-   Building a spectrogram
-   Characteristics and limitations
-   Spectrograms in R

&nbsp; 

<div class="alert alert-info">

### Project assignment

1. Double-check annotations using warbleR's dedicated functions
  - Create single spectrograms of each annotation
  - Create full spectrograms of all sound files along with annotations
  - Create catalogs

&nbsp; 

2. Double-check annotations using Raven (export data from R to Raven)

</div>


---

&nbsp; 

## Day 4

---

<div class="alert alert-warning">

### Readings 

#### 

- Odom, K. J., Cain, K. E., Hall, M. L., Langmore, N. E., Mulder, R. A., Kleindorfer, S., ... & Webster, M. S. (2021). [Sex role similarity and sexual selection predict male and female song elaboration and dimorphism in fairy‐wrens](https://onlinelibrary.wiley.com/doi/pdf/10.1002/ece3.8378). Ecology and evolution, 11(24), 17901-17919.


</div>

&nbsp; 


**Package seewave**
<a href="https://marce10.github.io/OTS_BIR_2023/seewave.html" class="btn btn-warning btn-xs" role="button">seewave</a>

-   Explore, modify and measure ‘wave’ objects
-   Spectrograms and oscillograms
-   Filtering and re-sampling
-   Acoustic measurements

**Quantifying acoustic signal structure**
<a href="https://marce10.github.io/OTS_BIR_2023/measure_acoustic_structure.html" class="btn btn-warning btn-xs" role="button">Quantify structure</a>

-   Spectro-temporal measurements (`spectro_analysis()`)
-   Parameter description
-   Harmonic content
-   Cepstral coefficients (`mfcc_stats()`)
-   Cross-correlation (`cross_correlation()`)
-   Dynamic time warping (`freq_DTW()`)
-   Signal-to-noise ratio (`sig2noise()`)
-   Inflections (`inflections()`)
-   Parameters at other levels (`song_analysis()`)
-   Acoustic space using Principal Component Analysis

&nbsp; 

<div class="alert alert-info">

### Project assignment

1. Select best quality signals for analysis
1. Measure acoustic parameters
1. Summarize variation at higher hierachical levels (if necessary)

</div>

---

&nbsp; 

## Day 5

---

**Quality control in recordings and annotation**
<a href="https://marce10.github.io/OTS_BIR_2023/quality_checks.html" class="btn btn-warning btn-xs" role="button">Quality checks</a>

-   Check and modify sound file format (`check_wavs()`, `info_wavs()`,
    `duration_wavs()`, `mp32wav()` y `fix_wavs()`)
-   Tuning spectrogram parameters (`tweak_spectro()`)
-   Double-checking selection tables (`check_sels()`, `spectrograms()`,
    `full_spectrograms()` & `catalog()`)
-   Re-adjusting selections (`tailor_sels()`)


&nbsp; 

<div class="alert alert-info">

### Project assignment

1. Plot acoustic spaces
1. Write report

*[Check out this guide on how to measure acoustic structure on Xeno-Canto recordings](https://marce10.github.io/OTS_BIR_2023/measure_structure_green_hermit.html)*


</div>

&nbsp;
